remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: L.B.Stanza
description: L.B. Stanza (or Stanza for short) is a new optionally-typed general purpose programming language from the University of California, Berkeley. Stanza was designed to help programmers tackle the complexity of architecting large programs and significantly increase the productivity of application programmers across the entire software development life cycle.
show_downloads: true
google_analytics: UA-77155883-1
